### ISSUE TITLE
Переделать алиасы команд на регулярные выражения.

### ISSUE THREAD

**Issue by Arslav** [Arslav/vk-bot#13]
Нужны регулярки на:

1. "ыыыы" (количество "ыыыы" произвольно)
2. "слава кто я" (со знаками препинания, вопросом на конце и т.д.). "кто" может быть заменено на "что"/"хто") https://regex101.com/r/vIjzES/1
3. "слава кто мы"

**Comment by Praenik** [comment]
1. /ы+/gm
2. слава(\,)*(  )*[к,ч,х]то(\,)*(  )*я(\?)*/gm
3.слава(\,)*(  )*[к,ч,х]то(\,)*(  )*мы(\?)*/gm

**Comment by Arslav** [comment]
@Praenik, убери ``/gm`` и ``*`` (ноль или более) замени на ``?`` (ноль или одно). Добавь символы начала ``^`` и конца строки ``$``
